import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy initialization of GoogleGenAI
function getGenAI() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is missing.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// AI Chatbot Route
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, portalContext } = req.body;

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: "Invalid messages payload." });
    }

    const ai = getGenAI();

    // Build context string from live portal database
    let contextText = "No portal database snapshot provided.";
    if (portalContext) {
      const { cases, landDisputes, udCases, ios, dailyReports, userRole, userPS } = portalContext;

      contextText = `
SYSTEM DATABASE SNAPSHOT (CURRENT LIVE PORTAL DATA):
Active User Role: ${userRole || "SDPO"}
Active Police Station Context: ${userPS || "All Police Stations (SDPO Tarapur)"}

--- FIR CASES (${cases?.length || 0} TOTAL) ---
${JSON.stringify(cases || [], null, 2)}

--- LAND DISPUTES (${landDisputes?.length || 0} TOTAL) ---
${JSON.stringify(landDisputes || [], null, 2)}

--- UD (UNNATURAL DEATH) CASES (${udCases?.length || 0} TOTAL) ---
${JSON.stringify(udCases || [], null, 2)}

--- INVESTIGATING OFFICERS / IOs (${ios?.length || 0} TOTAL) ---
${JSON.stringify(ios || [], null, 2)}

--- DAILY CRIME REPORTS (${dailyReports?.length || 0} TOTAL) ---
${JSON.stringify(dailyReports || [], null, 2)}
`;
    }

    const systemInstruction = `
You are "Tarapur AI Assistant", an intelligent police subdivision AI assistant & data analyst for SDPO Tarapur (Sub-Divisional Police Officer) in Bihar, India.
Your task is to answer questions, query police database records, list specific case details, provide supervision summaries, track 60/90-day investigation deadlines, monitor IO workloads, land disputes, UD cases, and daily crime reports.

CRITICAL INSTRUCTIONS & BEHAVIOR:
1. DATA ACCURACY: Always query and analyze the provided LIVE PORTAL DATA SNAPSHOT below. Do not invent fake FIR numbers, IO names, or case statuses.
2. FLEXIBLE QUERY HANDLING:
   - Murder cases: Filter FIR cases where sections or crime category includes murder, 302 IPC, 103 BNS, or murder/homicide keywords.
   - Pending Supervision cases: Filter cases where designation is 'SR' or status is 'Pending', or sdpoSupervisionNote exists/missing, or supervision is requested/required.
   - Specific IO cases: Filter cases where ioName matches or contains the IO name asked by user (e.g. "Inspector Kumar", "Ram", "Singh").
   - Deadline compliance: Calculate days elapsed since FIR date or date of occurrence and compare against target deadlines (60 days for normal, 90 days for major crimes).
   - Land Disputes & UD Cases: Extract and report exact details from the land disputes and UD case arrays.
3. OUTPUT FORMATTING:
   - Use clean Markdown formatting (bold headers, bullet points, structured tables when listing multiple cases).
   - Highlight key metadata for cases: FIR No., Police Station (PS), Sections/IPC/BNS, Case Status, IO Name, Date of Occurrence, Target Deadline, CCTNS status, Supervision Directives.
   - Keep answers professional, concise, authoritative, and helpful to police officers, CIs, and SDPO.
   - If no matching cases are found in the database, clearly inform the user and state what was checked.

${contextText}
`;

    // Format conversation history
    const history = messages.slice(0, -1);
    const lastUserMessage = messages[messages.length - 1].content;

    let formattedPrompt = "";
    if (history.length > 0) {
      formattedPrompt += "Previous conversation history:\n";
      history.forEach((m: { role: string; content: string }) => {
        formattedPrompt += `${m.role.toUpperCase()}: ${m.content}\n`;
      });
      formattedPrompt += "\nLatest User Question:\n";
    }
    formattedPrompt += lastUserMessage;

    const response = await ai.models.generateContent({
      model: "gemini-3.8-flash",
      contents: formattedPrompt,
      config: {
        systemInstruction,
        temperature: 0.2,
      },
    });

    const replyText = response.text || "No response generated by Gemini AI.";
    return res.json({ text: replyText });
  } catch (error: any) {
    console.error("Error in /api/chat:", error);
    return res.status(500).json({
      error: error.message || "Failed to generate AI response.",
    });
  }
});

// AI Batch Crime Classification Endpoint
app.post("/api/classify-crimes", async (req, res) => {
  try {
    const { cases } = req.body;
    if (!cases || !Array.isArray(cases) || cases.length === 0) {
      return res.status(400).json({ error: "No cases provided for classification." });
    }

    const ai = getGenAI();
    const prompt = `You are a Bihar Police Law & Crime Head Classification System.
Classify each of the following FIR cases into EXACTLY one of these standardized Crime Heads:
- Murder
- Mob Lynching
- Culpable Homicide
- Attempt to Murder
- Dacoity
- Robbery / Loot
- Extortion / Rangdari
- Snatching
- Theft
- Stolen Property
- Electric Energy Theft
- Kidnapping / Abduction
- Dowry Death
- Sec 69 BNS (Sexual Deceit)
- Rape
- POCSO Act
- Molestation / Outraging Modesty
- Cruelty by Husband (85 BNS / 498A)
- Dowry Prohibition Act
- SC/ST Act
- Immoral Traffic (ITPA) Act
- Child Labour Act
- Arms Act
- Explosive Substances Act
- Essential Commodities Act
- IT Act / Cyber Crime
- NDPS Act
- Awaidh Khanan (Illegal Mining)
- Forgery / Cheating (318, 319 BNS)
- Aarthik Gaban (316 BNS / CBT)
- Other / General IPC & BNS

Here are the FIR Cases to classify:
${JSON.stringify(
  cases.map((c: any) => ({
    id: c.id,
    firNumber: c.firNumber,
    ps: c.ps,
    sections: c.sections,
    complainantName: c.complainantName,
    placeOfOccurrence: c.placeOfOccurrence,
    isArmsCase: c.isArmsCase,
    isNdpsCase: c.isNdpsCase,
    isVictimRecoveryCase: c.isVictimRecoveryCase,
  })),
  null,
  2
)}

Return a JSON array of objects with schema: [{"id": "...", "crimeHead": "...", "confidence": 0.95, "reasoning": "..."}].
Output STRICT valid JSON only without markdown formatting.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.8-flash",
      contents: prompt,
      config: {
        temperature: 0.1,
        responseMimeType: "application/json",
      },
    });

    const parsedResults = JSON.parse(response.text || "[]");
    return res.json({ classifications: parsedResults });
  } catch (error: any) {
    console.error("Error in /api/classify-crimes:", error);
    return res.status(500).json({
      error: error.message || "Failed to classify crimes with AI.",
    });
  }
});

const RAPID_KEY = process.env.RAPID_API_KEY || '5f2b24e02emsh645a917bb3f6b5bp1734bbjsn30ba61c92d78';
const RAPID_HOST = process.env.RAPID_API_HOST || 'google-map-places-new-v2.p.rapidapi.com';
const GOOGLE_API_KEY = process.env.GOOGLE_MAPS_PLATFORM_KEY || process.env.VITE_GOOGLE_MAPS_PLATFORM_KEY || '';

// Server-side Geocode & Place Search Proxy (Google Maps Places New V2 API)
app.get("/api/geocode", async (req, res) => {
  try {
    const address = (req.query.address as string || '').trim();
    if (!address) {
      return res.status(400).json({ error: "Missing address query parameter." });
    }

    const biasLat = parseFloat(req.query.lat as string) || 25.1228;
    const biasLng = parseFloat(req.query.lng as string) || 86.6492;

    const searchQueries = [
      address,
      `${address}, Bihar, India`,
      `${address}, India`,
    ];

    // 1. Query Official Google Maps Places New V2 SearchText via RapidAPI
    for (const q of searchQueries) {
      try {
        const rRes = await fetch(`https://${RAPID_HOST}/v1/places:searchText`, {
          method: 'POST',
          headers: {
            'x-rapidapi-key': RAPID_KEY,
            'x-rapidapi-host': RAPID_HOST,
            'Content-Type': 'application/json',
            'X-Goog-FieldMask': 'places.displayName,places.formattedAddress,places.location',
          },
          body: JSON.stringify({
            textQuery: q,
            locationBias: {
              circle: {
                center: { latitude: biasLat, longitude: biasLng },
                radius: 45000.0,
              },
            },
          }),
        });

        if (rRes.ok) {
          const data: any = await rRes.json();
          const place = data.places?.[0];
          if (place?.location && typeof place.location.latitude === 'number' && typeof place.location.longitude === 'number') {
            return res.json({
              latitude: Number(place.location.latitude.toFixed(5)),
              longitude: Number(place.location.longitude.toFixed(5)),
              name: place.displayName?.text || address,
              formattedAddress: place.formattedAddress || place.displayName?.text || address,
              source: 'GOOGLE_MAPS_OFFICIAL',
            });
          }
        }
      } catch (err) {
        // continue
      }
    }

    // 2. Try Google Maps Platform API if key configured
    if (GOOGLE_API_KEY) {
      try {
        const gRes = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${GOOGLE_API_KEY}`);
        if (gRes.ok) {
          const gData: any = await gRes.json();
          const loc = gData.results?.[0]?.geometry?.location;
          if (loc && typeof loc.lat === 'number' && typeof loc.lng === 'number') {
            return res.json({
              latitude: Number(loc.lat.toFixed(5)),
              longitude: Number(loc.lng.toFixed(5)),
              formattedAddress: gData.results[0].formatted_address || address,
              source: 'GOOGLE_MAPS_API',
            });
          }
        }
      } catch (err) {
        // continue
      }
    }

    // 3. Try Photon Komoot Geocoder (Very tolerant to Indian locality names)
    try {
      const photonRes = await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(address)}&limit=1`);
      if (photonRes.ok) {
        const pData: any = await photonRes.json();
        const feat = pData.features?.[0];
        if (feat && feat.geometry?.coordinates) {
          const [lon, lat] = feat.geometry.coordinates;
          const props = feat.properties || {};
          const name = [props.name, props.city || props.district, props.state, props.country].filter(Boolean).join(', ');
          return res.json({
            latitude: Number(lat.toFixed(5)),
            longitude: Number(lon.toFixed(5)),
            formattedAddress: name || address,
            source: 'PHOTON_GIS',
          });
        }
      }
    } catch (err) {
      // continue
    }

    // 4. Try OpenStreetMap Nominatim
    try {
      const osmRes = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(address)}&limit=1`, {
        headers: { 'User-Agent': 'BiharPoliceGIS/1.0' },
      });
      if (osmRes.ok) {
        const osmData: any = await osmRes.json();
        if (osmData && osmData[0]) {
          const lat = parseFloat(osmData[0].lat);
          const lon = parseFloat(osmData[0].lon);
          if (!isNaN(lat) && !isNaN(lon)) {
            return res.json({
              latitude: Number(lat.toFixed(5)),
              longitude: Number(lon.toFixed(5)),
              formattedAddress: osmData[0].display_name || address,
              source: 'NOMINATIM_OSM',
            });
          }
        }
      }
    } catch (err) {
      // continue
    }

    return res.status(404).json({ error: "Location not found." });
  } catch (error: any) {
    console.error("Error in /api/geocode:", error);
    return res.status(500).json({ error: error.message || "Failed to geocode address." });
  }
});

// Server-side Autocomplete Suggestions Proxy (Google Maps Search)
app.get("/api/places/autocomplete", async (req, res) => {
  try {
    const input = (req.query.input as string || '').trim();
    if (!input || input.length < 2) {
      return res.json({ suggestions: [] });
    }

    const biasLat = parseFloat(req.query.lat as string) || 25.1228;
    const biasLng = parseFloat(req.query.lng as string) || 86.6492;
    const suggestions: any[] = [];

    // 1. Query Google Maps Places New V2 via RapidAPI
    try {
      const rRes = await fetch(`https://${RAPID_HOST}/v1/places:searchText`, {
        method: 'POST',
        headers: {
          'x-rapidapi-key': RAPID_KEY,
          'x-rapidapi-host': RAPID_HOST,
          'Content-Type': 'application/json',
          'X-Goog-FieldMask': 'places.displayName,places.formattedAddress,places.location',
        },
        body: JSON.stringify({
          textQuery: input,
          locationBias: {
            circle: {
              center: { latitude: biasLat, longitude: biasLng },
              radius: 45000.0,
            },
          },
        }),
      });

      if (rRes.ok) {
        const data: any = await rRes.json();
        const items = data.places || [];
        for (const it of items.slice(0, 8)) {
          const loc = it.location;
          if (loc && typeof loc.latitude === 'number' && typeof loc.longitude === 'number') {
            const lat = Number(loc.latitude.toFixed(5));
            const lng = Number(loc.longitude.toFixed(5));
            suggestions.push({
              name: it.displayName?.text || it.formattedAddress,
              formattedAddress: it.formattedAddress || it.displayName?.text,
              lat,
              lng,
              source: 'Google Maps Places',
            });
          }
        }
      }
    } catch (err) {
      // continue
    }

    // 2. Query Photon Komoot Geocoder if fewer than 4 results
    if (suggestions.length < 4) {
      try {
        const pRes = await fetch(`https://photon.komoot.io/api/?q=${encodeURIComponent(input)}&limit=4`);
        if (pRes.ok) {
          const pData: any = await pRes.json();
          const feats = pData.features || [];
          for (const f of feats) {
            const [lon, lat] = f.geometry?.coordinates || [];
            const props = f.properties || {};
            const name = props.name || props.street || input;
            const full = [props.name, props.district || props.city, props.state, props.country].filter(Boolean).join(', ');
            if (lat && lon && !suggestions.some(s => Math.abs(s.lat - lat) < 0.001 && Math.abs(s.lng - lon) < 0.001)) {
              suggestions.push({
                name,
                formattedAddress: full || name,
                lat: Number(lat.toFixed(5)),
                lng: Number(lon.toFixed(5)),
                source: 'GIS Global Places',
              });
            }
          }
        }
      } catch (err) {
        // continue
      }
    }

    return res.json({ suggestions });
  } catch (error: any) {
    console.error("Error in /api/places/autocomplete:", error);
    return res.status(500).json({ error: error.message || "Failed to fetch suggestions." });
  }
});


async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
